name: Hello World Training Workflow

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    env:
        MY_ENV: "Landeon09"

    steps:
      - name: Run a multi-line script
        run: |
          echo "Hello $MY_ENV"
          echo "Hello $GITHUB_ACTOR"
              # List all files in the current directory for comparison before and after actions/checkout@v5.
      - run: ls -l
      - uses: actions/checkout@v5
      - run: ls -l
