name: Hello World Training Workflow

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Hello World!"
      - name: list all files in the folder
        run: ls -la
      - name: Download Source code
        uses: actions/checkout@v5
      - name: list all files after the source downloaded
        run: ls -la
